Feat/parent location
Duna-System/duna-web-platform-db pull request #2
Opened 2023-11-15 16:45 UTC by Marcus-D-Forte

2023-11-17 15:11 UTC, EliasFernandes03 approved these changes

2023-11-19 14:50 UTC, brunonnalvesduna approved these changes

2023-11-19 15:11 UTC, sedoski-duna requested changes

2023-11-19 15:11 UTC, sedoski-duna commented on README.md
> +
Fiz um teste essa semana e tambem da pra usar a versao local. Foi bem util pra testes durante a implementacao, ai soh dou o commit quando ta tudo finalizado. 

Basicamente no repositorio pai, basta mudar o `package.json` pra apontar pro caminho do repositorio local buildado, em seguida chamar npm install.

2023-11-19 15:11 UTC, sedoski-duna commented on build/entity/services/EntityService.d.ts
> +    assignParentName(project_id: string, entity_name: string, parent_entity_name: string): Promise<void>;
Faz sentido essa logica de negocio estar nesse repo? No meu entendimento o projects deveria setar a propriedade `parent` e enviar o documento para o db.

2023-11-19 15:11 UTC, sedoski-duna commented on src/entity/services/EntityService.ts
> +    /**
Assim como no comentario anterior, acredito que essa logica deveria estar um nivel acima na estrutura.
Podendo assim utilizar o endpoint de `updateEntity` que eh flexivel para atualizar um campo por vez

2023-11-20 16:01 UTC, Marcus-D-Forte commented on build/entity/services/EntityService.d.ts
> +    assignParentName(project_id: string, entity_name: string, parent_entity_name: string): Promise<void>;
Esse método funcionou fazer do jeito q c recomendou

2023-11-20 16:02 UTC, Marcus-D-Forte commented on src/entity/services/EntityService.ts
> +    /**
O método de promoção não funciona somente pelo `update`. Eu preciso acessar o Model, setar como undefined e chamar `save`

2023-11-20 18:47 UTC, sedoski-duna approved these changes

2023-11-21 01:54 UTC, merged