Feat/photogrammetry type
Duna-System/duna-web-platform-db pull request #8
Opened 2024-01-10 17:35 UTC by Marcus-D-Forte

Added photogrammetry entity

2024-01-12 16:58 UTC, brunonnalvesduna requested changes

2024-01-12 16:58 UTC, brunonnalvesduna commented on build/projects/validationProjectsDb.js
> +                            description: 'Entidade de fogotrametria [unica] (array de strings)',
Faltou mudar aqui pra inglês também

2024-01-12 16:58 UTC, brunonnalvesduna commented on src/projects/validationProjectsDb.ts
> +                            'Entidade de fogotrametria [unica] (array de strings)',
Faltou mudar aqui pra inglês também

2024-01-15 12:42 UTC, EliasFernandes03 approved these changes

2024-01-15 17:23 UTC, brunonnalvesduna approved these changes

2024-01-15 17:35 UTC, merged